repos:
  # Python - Ruff (formatter & linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # JavaScript/TypeScript - Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, css, scss, html, yaml, markdown]
        additional_dependencies:
          - prettier@3.1.0

  # JavaScript/TypeScript - ESLint (一時的に無効化)
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.0.0-beta.2
  #   hooks:
  #     - id: eslint
  #       files: frontend/.*\.(js|jsx|ts|tsx)$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@9.0.0-beta.2
  #         - "@typescript-eslint/eslint-plugin"
  #         - "@typescript-eslint/parser"

  # General - trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
